### ISSUE TITLE
Pagination bug

### ISSUE THREAD

**Issue by davemcorwin** [GSA/made-in-america#111]
On initial load of https://www.madeinamerica.gov/waivers/ the pagination link for "2" is repeated, see image. This goes away once i click on any of the pagination links.

Observed on Firefox 94.0.1 on MacOS Bug Sur 11.6

![Screen Shot 2021-11-18 at 9 30 22 AM](https://user-images.githubusercontent.com/6662371/142466740-0aa3b861-f8dc-403a-833e-1bc6cca7533f.png)

**Comment by brunerae** [comment]
Hi @davemcorwin - thanks for flagging this! It was fixed in https://github.com/GSA/made-in-america/commit/828a2c9db2524e074ca4f7551fd1abbf4d197373 so I'm going to close this.
